language: node_js

node_js:
- 8.11.2

branches:
  only:
  - develop

script:
  - npm run test

deploy:
  provider: heroku
  api_key:
    secure: o/PX9es5EA8xI2g5/E36K4D4cpRtsqnOdFXm/osF4H2CTGgjOTr6pCMpPIIhSsG7iEAxn0H2jetYKclu+i19vRMkJP5zoCApLXyJZO1YVUNFnYTU2UTCRwRBGSGu2r/T+4o6oyOM8dNPQZOI4Q0d2h3+OynXuavxYeZd3ZV5l+yGM96G3+2pLi0RifUV6IvJ7DwvpRc/fttEASXDlXfKzW1ePlMhdFovXTs6G1X8+C895A7kNxA4HSYCPycf2smB6QfhIkePu0jfXBQVbLnzzR7dWfVuXx39qXTZPQ+O6lAcDcr8tpbLE4uKewDaaJ7cy3SYOwO7sf/rz1BbbabvaLC3sDgNNU2a/Y+lvgt4MewfkfiNKq89XS4wpkbOUHYbSIselSMf3uUg0RnWL7T/Rq+KXYBEkaEhBNYUs9hQeP7XncCUWCZZ+8hxnLKTVpoAKULO9m7GUR81JwRM/QfXpMPyBKJchUgn4f2Z8I5cemXa8M8ZkLxpXPcwTvPorVRtNCXDS2QqmvCCDxqun5B04MOpiQg2sarMvY3XLEi7jMCr2fdnEqqzny7+CXNgNbmwULDKCKKMo5aG4YJhvpLlwBJb7u1DnstjSxFl/mCgZJfJJBdRWkHJwzBKi0msbIMlz95mO0kUUzgG+FuwR1m/Im61NndZo50VIrfEHCytyYY=
  app: loft-taxi-mihanizm56
  on: 
    branch: develop