
export const INPUT_NAME_OF_CARD = 'INPUT_NAME_OF_CARD';
export const INPUT_END_DATE_OF_CARD = 'INPUT_END_DATE_OF_CARD';
export const INPUT_NUMBER_OF_CARD = 'INPUT_NUMBER_OF_CARD';
export const INPUT_SECRET_CODE_OF_CARD = 'INPUT_SECRET_CODE_OF_CARD';
